steps:
  # Etapa 1: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chatbot-api', '.']

  # Etapa 2: Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chatbot-api']

  # Etapa 3: Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - chatbot-api
      - --image=gcr.io/$PROJECT_ID/chatbot-api
      - --region=southamerica-east1
      - --platform=managed
      - --allow-unauthenticated
      - --update-secrets=GCP_KEY_PATH_DESK=chatbot-key:latest

images:
  - 'gcr.io/$PROJECT_ID/chatbot-api'
