substitutions:
  _REGION: southamerica-east1
  _SERVICE_NAME: chatbot-api
  _SECRET_NAME: chatbot-key
  _ENV_VAR_NAME: GCP_KEY_PATH_DESK

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=gcr.io/$PROJECT_ID/$_SERVICE_NAME
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --update-secrets=$_ENV_VAR_NAME=$_SECRET_NAME:latest
      - --quiet

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
